version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: awsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - ola_network

  springboot:
    build: .
    container_name: employee_app
    ports:
      - "8091:8091"
    depends_on:
      - awsdb
    networks:
      - ola_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/awsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

networks:
  ola_network:
    driver: bridge
